import { Category, Product } from '@/types/product';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'sayur', name: 'Sayur & Buah', icon: '🥬' },
  { id: 'daging', name: 'Daging Segar', icon: '🍗' },
  { id: 'sembako', name: 'Sembako', icon: '🍚' },
  { id: 'minuman', name: 'Minuman', icon: '🥤' },
  { id: 'susu', name: 'Susu & Olahan', icon: '🥛' },
  { id: 'snack', name: 'Camilan', icon: '🍿' },
  { id: 'bumbu', name: 'Bumbu Dapur', icon: '🌶️' },
  { id: 'frozen', name: 'Frozen Food', icon: '🥟' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    sku: 'BRS-RAMOS-5KG',
    name: 'Beras Ramos Setra Premium 5kg',
    description: 'Beras pulen pilihan keluarga Baiturrahman Mart, tanpa pemutih dan wangi alami.',
    price: 69500,
    promoPrice: 64900,
    promoActive: true,
    discountPercent: 7,
    category: 'sembako',
    stock: 24,
    unit: 'sak',
    barcode: '8991234567890',
    isHalal: true,
    isBestSeller: true,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&q=80',
  },
  {
    id: 2,
    sku: 'MYK-TRP-2L',
    name: 'Minyak Goreng Tropical 2 Liter',
    description: 'Minyak goreng 2x penyaringan, jernih dan hemat.',
    price: 38500,
    promoPrice: 33500,
    promoActive: true,
    discountPercent: 13,
    category: 'sembako',
    stock: 18,
    unit: 'pouch',
    barcode: '8999876543210',
    isHalal: true,
    isBestSeller: true,
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80',
  },
  {
    id: 3,
    sku: 'TLR-AYM-10',
    name: 'Telur Ayam Negeri Fresh (Isi 10 Butir)',
    description: 'Telur segar pilihan langsung dari peternakan binaan masjid.',
    price: 26000,
    promoPrice: 24000,
    promoActive: true,
    discountPercent: 8,
    category: 'sembako',
    stock: 35,
    unit: 'pack',
    barcode: '8992345678901',
    isHalal: true,
    isBestSeller: true,
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=500&q=80',
  },
  {
    id: 4,
    sku: 'AYM-BRL-1KG',
    name: 'Daging Ayam Broiler Utuh Bersih 1kg',
    description: 'Diproses dengan pemotongan halal syar\'i Baiturrahman.',
    price: 38000,
    promoPrice: 34500,
    promoActive: true,
    discountPercent: 9,
    category: 'daging',
    stock: 12,
    unit: 'ekor',
    barcode: '8993456789012',
    isHalal: true,
    isBestSeller: false,
    imageUrl: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=500&q=80',
  },
  {
    id: 5,
    sku: 'SSU-ULT-1L',
    name: 'Susu UHT Ultra Milk Cokelat 1 Liter',
    description: 'Susu segar bernutrisi tinggi untuk anak dan keluarga.',
    price: 19500,
    category: 'susu',
    stock: 28,
    unit: 'kotak',
    barcode: '8994567890123',
    isHalal: true,
    isBestSeller: true,
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&q=80',
  },
  {
    id: 6,
    sku: 'MIE-IND-GRG',
    name: 'Indomie Goreng Spesial 85g (Pack 5 pcs)',
    description: 'Mi instan goreng legendaris Indonesia dengan bumbu gurih.',
    price: 15500,
    promoPrice: 14200,
    promoActive: true,
    discountPercent: 8,
    category: 'sembako',
    stock: 60,
    unit: 'pack',
    barcode: '8995678901234',
    isHalal: true,
    isBestSeller: true,
    imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&q=80',
  },
];
